[package]
name = "password_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26.4"
